### **Python NumPy Array**

In [1]:
import numpy as np

In [2]:
array_1 = np.array([10,20,30,40])
print(array_1)
print(array_1.shape)
print(array_1.size)
print(array_1.ndim)
print(array_1.dtype)

[10 20 30 40]
(4,)
4
1
int64


In [3]:
array_2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array_2)
print(array_2.shape)
print(array_2.size)
print(array_2.ndim)
print(array_2.dtype)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
9
2
int64


In [4]:
array_3 = np.array([[
    [10,20,30],
    [40,50,60]],
    [[10,20,30],
    [40,50,60]]])
print(array_3)
print(array_3.shape)
print(array_3.size)
print(array_3.ndim)
print(array_3.dtype)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]
(2, 2, 3)
12
3
int64


### **Type Casting**

In [5]:
array_2 = np.array([[10,20,30],[40,50,60],[70,80,"hi"]])
print(array_2.dtype)
print(array_2)

<U21
[['10' '20' '30']
 ['40' '50' '60']
 ['70' '80' 'hi']]


In [ ]:
array_2 = np.array([[10,20,30],[40,50,60],[70,80,"hi"]],dtype="int")
print(array_2)

In [ ]:
array_2 = np.array([[10,20,30],[40,50,60],[70,80,"90"]],dtype="float")
print(array_2)
print(array_2.dtype)

### **Array Filling**

In [ ]:
a = np.full((2,2,2),2)
print(a)

In [ ]:
a = np.full((2,2,3),"2")
print(a)
print(a.dtype)

In [ ]:
a = np.full((2,2,3),[2,3,4])
print(a)
print(a.dtype)

In [ ]:
a = np.full((2,2,3),["vendhan","mani","rithish"])
print(a)
print(a.dtype)

In [ ]:
b = np.zeros((5,5))
print(b)

In [ ]:
b = np.zeros((5,5),dtype="int")
print(b)

In [ ]:
c = np.ones((5,5))
print(c)

### **Arrange**

In [ ]:
for i in range(-10,11,3):
    print(i,end=" ")

In [ ]:
print(np.arange(-11,11,2))

In [ ]:
print(np.arange(100,0,-10))
print(np.arange(0,101,10))

### **linspace**

In [ ]:
x = np.linspace(0,200,100)
print(x)

### **nan,inf**

In [ ]:
# nan,
print(np.sqrt(25))
print(np.sqrt(-25))
print("hello")

In [ ]:
# inf,
print(np.array([10])/2)
print(np.array([10])/0)

### **python list**

In [ ]:
l1 = [1,2,3,4]
l2 = [4,5,6,7]
print(l1+l2)

In [ ]:
l1 = np.array([1,2,3,4])
l2 = np.array([4,5,6,7])
print(l1+l2)
print(l1*l2)
print(l2-l1)

In [ ]:
l1 = np.array([1,2,3,4])
l2 = np.array(
    [[2],
     [5]]
)
print(l1+l2)
print()
print(l1*l2)

In [ ]:
l1 = [1,2,3,4]
l1.append([6,7,8])
print(l1)
print(len(l1))

In [ ]:
l1 = np.array([1,2,3,4])
l2 = np.insert([l1],2,[6,7,8])
print(l2)
print(len(l2))

### **Delete array**

In [ ]:
l1 = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15]])
print(l1)
print()
print(np.delete(l1,[10,11,12]))
print()
print(np.delete(l1,[3],1))
print()
print(np.delete(l1,1,0))


In [ ]:
l2 = np.array([[[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]],
                [[16,17,18,19,20],
                [21,22,23,24,25],
                [26,27,28,29,30]]])
print(l2)
print()
print(np.delete(l2,[10,11,12]))
print()
print(np.delete(13,1,0))


### **Array filling random**

In [ ]:
np.random.seed(2)
a = np.random.random((5,5))
print(a)

In [ ]:
np.random.seed(3)
a = np.random.randint(1,10,size=(5,5))
print(a)

In [ ]:
print(np.unique(a))

### **identical matrix**

In [ ]:
print(a)

In [ ]:
b = np.full((5,5),2)
print(b)

In [ ]:
print(a+b)
print()
print(a*b)
print()
print(a-b)

### **non-identical matrix**

In [ ]:
print(a)

In [ ]:
np.random.seed(3)
b = np.random.randint(1,5,size=(5,1))
print(b)

In [ ]:
print(a+b)

In [ ]:
np.random.seed(3)
c = np.random.randint(1,5,size=(5))
print(c)

In [ ]:
print(a+c)

In [ ]:
print(a)

In [ ]:
print(a[:3,:3])

In [ ]:
print(a[2:,2:])

In [ ]:
np.random.seed(2)
a = np.random.random((5,5))
print(a)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,6,4,5])
print(arr)